### ISSUE TITLE
EXCEPTION: St12out_of_range in updatebids, core dump

### ISSUE THREAD

**Issue by thelonecrouton** [bitcreditscc/bitcredit#48]
Full stdout error:

************************
EXCEPTION: St12out_of_range       
basic_string::substr: __pos (which is 18446744073709551615) > this->size() (which is 0)       
bitcredit in updatebids       

terminate called after throwing an instance of 'std::out_of_range'
  what():  basic_string::substr: __pos (which is 18446744073709551615) > this->size() (which is 0)
Aborted (core dumped)

**Comment by bitcreditscc** [comment]
this is an exception being caught by the bidtracker, it parses text using manual manip, which is very inflexible. working on json implementation.

**Comment by bitcreditscc** [comment]
temporary work around added , git pull and let me know
